### ISSUE TITLE
你少了个实体类吧

### ISSUE THREAD

**Issue by wyy16318** [WelliJohn/charts#1]
ChildBean childBean = new ChildBean();
                childBean.setChildName("WelliJohn");
                childBean.setPrice(99.9);

**Comment by wyy16318** [comment]
F:\Studio_worSpace\charts-master\charts-master\app\src\main\java\wellijohn\org\charts\bean\BaseBean.java
Error:(53, 13) 错误: 找不到符号
符号: 类 ChildBean
Error:(53, 39) 错误: 找不到符号
符号: 类 ChildBean
Error:(61, 24) 错误: 找不到符号
符号: 类 ChildBean
F:\Studio_worSpace\charts-master\charts-master\app\src\main\java\wellijohn\org\charts\MainActivity.java
Error:(32, 17) 错误: 找不到符号
符号: 类 ChildBean
F:\Studio_worSpace\charts-master\charts-master\app\src\main\java\wellijohn\org\charts\PercentActivity.java
Error:(12, 33) 错误: 找不到符号
符号:   类 ChildBean
位置: 程序包 wellijohn.org.charts.bean
Error:(32, 43) 错误: 找不到符号
符号: 类 ChildBean
Error:(32, 9) 错误: 找不到符号
符号:   类 ChildBean
位置: 类 PercentActivity
Error:(32, 33) 错误: 找不到符号
符号:   类 ChildBean
位置: 类 PercentActivity
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by WelliJohn** [comment]
嗯嗯，已经修复了，你重新pull下吧
